# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"FastDataDataframeUtilities": "00_core.ipynb",
         "FastDataSeriesUtilities": "00_core.ipynb",
         "extract_number_from_string": "00_core.ipynb",
         "bin_column": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://molinsp.github.io/fastdata/"

git_url = "https://github.com/molinsp/fastdata/tree/master/"

def custom_doc_links(name): return None
