# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['FastDataUtilities']

# Cell
import pandas as pd
import numpy as np

@pd.api.extensions.register_dataframe_accessor('fdt')
class FastDataUtilities:
    def __init__(self, pandas_obj):
        self._obj = pandas_obj

    def flatten_multiindex(self,axis='all'):
        df = self._obj
        if 'MultiIndex' in str(type(df.columns)) and axis in ('all', 'columns'):
            df.columns = df.columns.map(lambda x: '_'.join([str(i) for i in x]))
        if 'MultiIndex' in str(type(df.index)) and axis in ('all', 'index'):
            df = df.reset_index()
        return df