package:
  name: fastdata
  version: 0.0.22
source:
  sha256: 8f9220e66a9d8b80131eecf564617e6a801680f235956ed0826679956d708b9d
  url: https://files.pythonhosted.org/packages/5f/7d/f665f3b7e344b958e14de1b874cbfb89d1cc5b25b2b0f33857b33f14c19d/fastdata-0.0.22.tar.gz
about:
  dev_url: https://molinsp.github.io
  doc_url: https://molinsp.github.io
  home: https://molinsp.github.io
  license: Apache Software
  license_family: APACHE
  summary: A library to accelerate data-science productivity with Pandas. Best used
    with the eigendata jupyterlab extension.
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - molinsp
requirements:
  host:
  - pip
  - python
  - packaging
  - pandas>=1.0.0
  - numpy>=1.0.0
  - fastcore>=1.1.0
  - jmespath>=0.10.0
  - gspread>=3.6.0
  - gspread-pandas>=2.2.3
  - pyairtable>=1.0.0
  run:
  - pip
  - python
  - packaging
  - pandas>=1.0.0
  - numpy>=1.0.0
  - fastcore>=1.1.0
  - jmespath>=0.10.0
  - gspread>=3.6.0
  - gspread-pandas>=2.2.3
  - pyairtable>=1.0.0
test:
  imports:
  - fastdata
